services:
  - type: web
    name: pothole-detection-api
    env: python
    buildCommand: pip install -r requirements_cloud.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 10000